from cta.data.resource_data import ResourceData
from cta.data.resource_configuration_data import ResourceConfigurationData
from cta.resources_waste_information import ResourcesWasteInformation
from cta.choosing_technological_process import ChoosingTechnologicalProcess
